import { ThemeVariables } from '../../@types/theme';

export default function ({}: ThemeVariables) {
  return {
    logo: require('./assets/images/tom_light.png'),
    
    sparkles: {
      topLeft: require('./assets/images/sparkles-top-left.png'),
      top: require('./assets/images/sparkles-top.png'),
      topRight: require('./assets/images/sparkles-top-right.png'),
      right: require('./assets/images/sparkles-right.png'),
      bottomRight: require('./assets/images/sparkles-bottom-right.png'),
      bottom: require('./assets/images/sparkles-bottom.png'),
      bottomLeft: require('./assets/images/sparkles-bottom-left.png'),
      BatmanSlider:require('./assets/images/BatmanSlider.png'),
      Joker12:require('./assets/images/Joker12.png'),
      Slider2:require('./assets/images/Slider2.png'),
      Slider3:require('./assets/images/PosterHullk.png'),
      Slider4:require('./assets/images/PosterGuardianofGalaxsi.png'),
      Slider5:require('./assets/images/PosterAv.png'),
      Layar:require('./assets/images/Layar.png'),
      Sukses:require('./assets/images/SuksesPaymet.png'),
      BacgroundLogin:require('./assets/images//image1.png'),
      Bg:require('./assets/images/bgLogin.png'),
      LogoLazada:require('./assets/images//LazadaLogo.png'),
      frame:require('./assets/images/Frame.png'),
      Background:require('./assets/images/bg12.png'),
      Backgroundkoin:require('./assets/images/bg13.png'),
      BackgroundBPJS:require('./assets/images/iconBpjs.png'),
      BackgroundDanaBills:require('./assets/images/DanaBills.png'),
      BackgroundIcomers:require('./assets/images/Iconicomers.png'),
      BackgroundPulsa:require('./assets/images/iconPulsa.png'),
      BackgroundSpill:require('./assets/images/Bgspill.png'),
      BackgroundGas:require('./assets/images/BackgroundGas.png'),
      BackgroundTelkom:require('./assets/images/BackgroundTelkom.png'),
      BackgroundParkir1:require('./assets/images/BacgroundParlir1.png'),
      BackgroundParrkir2:require('./assets/images/BackgroundParkir2.png'),
      BackgroundWatter:require('./assets/images/IconWatter2.png'),
      BackgroundWatter2:require('./assets/images/water2.png'),
      BackgroundWatter3:require('./assets/images/water3.png'),
      BackgroundBpjs:require('./assets/images/KartuBPJS.png'),
      Strukindighome:require('./assets/images/bayarindihome.jpeg'),
      StrukListrik:require('./assets/images/strukListrik.jpeg'),
     StrukAir:require('./assets/images/STRUKbayarair.jpeg'),
     StrukGas:require('./assets/images/pembayarngas.jpeg'),
     Samsat:require('./assets/images/Samsat12.png'),
     Etilang:require('./assets/images/Password.png'),
    },
    icons: {
      colors: require('./assets/images/colorswatch.png'),
      send: require('./assets/images/send.png'),
      translate: require('./assets/images/translate.png'),
      IconHomeOn: require('./assets/images/IconHomeOn.png'),
      IconHomeOff: require('./assets/images/IconHomeOff.png'),
      IconFavoritOn: require('./assets/images/IconFavoritOn.png'),
      IconFavoritOff: require('./assets/images/IconFavoritOff.png'),
      IconTiketOn: require('./assets/images/IconTiketOn.png'),
      IconTiketOff: require('./assets/images/IconHomeOff.png'),
      IconProfileOn: require('./assets/images/IconProfileOn.png'),
      IconProfileOff: require('./assets/images/IconProfilOff.png'),
      IconX: require('./assets/images/X.png'),
      Dana:require('./assets/images/IconDana.png'),
      IconMata:require('./assets/images/eye.png'),
      IconPesan:require('./assets/images/Pesannn1.png'),
      IconScan:require('./assets/images/Scan2.png'),
      iconTopUp:require('./assets/images/TopUp1.png'),
      iconSend:require('./assets/images/SendUang.png'),
      iconrequest:require('./assets/images/MintaUang.png'),
      Profile:require('./assets/images/Profile12.png'),
      Home:require('./assets/images/asik12.png'),
      icon12:require('./assets/images/icon12.png'),
      iconqr:require('./assets/images/qr.png'),
      iconRight:require('./assets/images/right.png'),
      iconUp:require('./assets/images/Up.png'),
      iconDown:require('./assets/images/Down.png'),
      iconGift:require('./assets/images/giftbox.png'),
      iconInformasion:require('./assets/images/information12.png'),
      iconInformasion2:require('./assets/images/information2.png'),
      iconTanya:require('./assets/images/question2.png'),
      iconDjp1:require('./assets/images/djp1.png'),
      iconDjp2:require('./assets/images/djp2.png'),
    },
  };
}
