export const Datamart = [
  {
    id: '1',
    name: 'DANA DEALS',
    images: require('../theme/assets/images/Alfamart.png'),
    alamat: 'Alfamart\nUjung Harapan',
    Km: '200 m',
    desc: 'Top Up Agent',
  },
  {
    id: '2',
    name: 'DANA DEALS',
    images: require('../theme/assets/images//Alfamart.png'),
    alamat: 'Alfamart\nUjung Harapan',
    agen: 'Top Up Agent',
    Km: '244 m',
    desc: 'Top Up Agent',
  },

  {
    id: '3',
    name: 'DANA DEALS',
    images: require('../theme/assets/images/Alfamart.png'),
    alamat: 'Alfamart\nUjung Harapan',
    agen: 'Top Up Agent',
    Km: '300 m',
  },
  {
    id: '4',
    name: 'DANA DEALS',
    images: require('../theme/assets/images/familly.png'),
    alamat: 'FamillyMart \n Chandra baga',
    agen: 'Top Up Agent',
    Km: '80 m',
    desc: 'Top Up Agent',
  },
  {
    id: '5',
    name: 'DANA DEALS',
    images: require('../theme/assets/images/prima.png'),
    alamat: 'Prima\nUjung Harapan',
    agen: 'Top Up Agent',
    Km: '700 m',
  },
  {
    id: '6',
    name: 'DANA DEALS',
    images: require('../theme/assets/images/prima.png'),
    alamat: 'Prima\nUjung Harapan',
    agen: 'Top Up Agent',
    Km: '209 m',
  },
  {
    id: '7',
    name: 'DANA DEALS',
    images: require('../theme/assets/images/familly.png'),
    alamat: 'FamillyMart \nUjung Harapan',
    agen: 'Top Up Agent',
    Km: '210 m',
    desc: 'Top Up Agent',
  },
];
