export const DataNews = [
  {
    id: '1',
    des: '#BukanDompetBiasa',
    images: require('../theme/assets/images/Bukadompet.png'),
    des1: 'Semua Transaki Bisa Di Dana',
  },
  {
    id: '2',
    des: 'Bye Modus Penipu',
    images: require('../theme/assets/images/Penipu.png'),
    des1: 'Cek tips aman DANA yuk!',
  },

  {
    id: '3',
    des: 'Serba Diskon Lazada',
    images: require('../theme/assets/images/LazadaLogo.png'),
    des1: 'Pakai DANA Diskon s/d Rp40RP!',
  },
  {
    id: '4',
    des: 'Proteksi Berkuliner',
    images: require('../theme/assets/images/friedchicken.png'),
    des1: 'Bikin Kuliner makin aman',
  },
  {
    id: '5',
    des: 'Proteksi Tagihan DANA',
    images: require('../theme/assets/images/credit2.png'),
    des1: 'Cek cara cepat klaimnya',
  },
  {
    id: '6',
    des: 'Asuransi Gadget DANA',
    images: require('../theme/assets/images/mobile.png'),
    des1: 'Cek cara cepat klaimnya',
  },
  {
    id: '7',
    des: 'Tips Jaga Datamu',
    images: require('../theme/assets/images/robbery.png'),
    des1: 'biar transaksi makin aman',
  },
  {
    id: '8',
    des: 'Pakai Kirim ke Grup',
    images: require('../theme/assets/images/people.png'),
    des1: 'Transaksi praktis ke banyak orang',
  },
  {
    id: '9',
    des: 'Mulai Dana Goals',
    images: require('../theme/assets/images/goals.png'),
    des1: 'wujudkan mimpi 2023-mu!',
  },
  {
    id: '10',
    des: 'Cek Langsung di Dana',
    images: require('../theme/assets/images/insurance.png'),
    des1: 'Status kirim uang & keluhanmu!',
  },
  {
    id: '12',
    des: 'Hemat 90% di A+ Rewards',
    images: require('../theme/assets/images/voucher.png'),
    des1: 'Serbu Voucernya sekarang!',
  },
  {
    id: '13',
    des: 'Asik Merchant Baru!',
    images: require('../theme/assets/images/asik.png'),
    des1: 'Cari Merchant favoritmu yuk',
  },
  {
    id: '14',
    des: 'Limit di DANA Deals!',
    images: require('../theme/assets/images/limited.png'),
    des1: 'Cek info updatenya di sini',
  },
  {
    id: '15',
    des: 'Beli Tiket Kereta Api!',
    images: require('../theme/assets/images/onlinebooking.png'),
    des1: 'Lebih Mudah di Dana',
  },
  {
    id: '16',
    des: 'Aman Nonton di Bioskop',
    images: require('../theme/assets/images/popcorn.png'),
    des1: 'Bareng TIX ID & DANA',
  },
  {
    id: '17',
    des: 'Pakai face Login di Dana',
    images: require('../theme/assets/images/faceid.png'),
    des1: 'Aman cepat & praktis',
  },
  {
    id: '18',
    des: 'Saldo TikTok Transfer ke Dana',
    images: require('../theme/assets/images/tiktok.png'),
    des1: 'ini cara dapetin & transfernya!',
  },
  {
    id: '19',
    des: 'DANA Delivery',
    images: require('../theme/assets/images/fooddelivery.png'),
    des1: 'pilih kurir untuk paketmu',
  },
  {
    id: '20',
    des: 'Baru di Nearby',
    images: require('../theme/assets/images/qrscan.png'),
    des1: 'Review toko favoritmu',
  },
  {
    id: '21',
    des: 'Hati-Hati Kirim Uang',
    images: require('../theme/assets/images/warning.png'),
    des1: 'Penipuan dengan Virtual Accunt',
  },
  {
    id: '22',
    des: 'Belanja dengan Dana',
    images: require('../theme/assets/images/shopping.png'),
    des1: 'Nikmati Belanja dengan dana',
  },
  {
    id: '23',
    des: 'Bayar Parkir dengan Dana',
    images: require('../theme/assets/images/parkir.png'),
    des1: 'Bayar Parkir lebih mudah dengan  DANA!',
  },
];
